In [1]:
import numpy as np
import torch

In [2]:
tensor_A = torch.randn(3, 3)
print(tensor_A)

tensor([[ 1.8183, -0.3605,  0.9639],
        [ 0.5819,  0.3147,  0.2236],
        [-0.2409,  0.9021, -0.7698]])


In [3]:
tensor_B = torch.linalg.inv(tensor_A)
print(tensor_B)

tensor([[ 1.1992, -1.5992,  1.0371],
        [-1.0646,  3.1537, -0.4171],
        [-1.6229,  4.1962, -2.1123]])


In [4]:
tensor_C = tensor_A @ tensor_B
print(tensor_C)

tensor([[ 1.0000e+00, -4.7684e-07,  0.0000e+00],
        [ 5.9605e-08,  1.0000e+00,  2.9802e-08],
        [ 2.3842e-07,  0.0000e+00,  1.0000e+00]])


In [5]:
tensor_A_grad=torch.gradient(tensor_A)
print("Gradient along rows:\n", tensor_A_grad[0])
print("Gradient along columns:\n", tensor_A_grad[1])

Gradient along rows:
 tensor([[-1.2363,  0.6752, -0.7403],
        [-1.0296,  0.6313, -0.8668],
        [-0.8228,  0.5874, -0.9934]])
Gradient along columns:
 tensor([[-2.1787, -0.4272,  1.3244],
        [-0.2672, -0.1792, -0.0911],
        [ 1.1430, -0.2645, -1.6719]])
