In [7]:
import numpy as np
import torch

In [12]:
tensor_A = torch.randn(3, 3)
print(tensor_A)

tensor([[-0.7807,  0.5576,  1.8620],
        [-0.9789,  1.0448,  0.0541],
        [ 0.5867,  2.2906,  1.2238]])


In [13]:
tensor_B = torch.linalg.inv(tensor_A)
print(tensor_B)

tensor([[-0.2087, -0.6476,  0.3462],
        [-0.2223,  0.3702,  0.3218],
        [ 0.5161, -0.3824,  0.0488]])


In [14]:
tensor_C = tensor_A @ tensor_B
print(tensor_C)

tensor([[ 1.0000e+00,  0.0000e+00, -2.2352e-08],
        [ 1.8626e-08,  1.0000e+00, -1.2107e-08],
        [ 0.0000e+00,  0.0000e+00,  1.0000e+00]])


In [19]:
tensor_A_grad=torch.gradient(tensor_A)
print("Gradient along rows:\n", tensor_A_grad[0])
print("Gradient along columns:\n", tensor_A_grad[1])

Gradient along rows:
 tensor([[-0.1982,  0.4873, -1.8080],
        [ 0.6837,  0.8665, -0.3191],
        [ 1.5655,  1.2457,  1.1697]])
Gradient along columns:
 tensor([[ 1.3383,  1.3214,  1.3045],
        [ 2.0237,  0.5165, -0.9908],
        [ 1.7039,  0.3186, -1.0668]])
